# Required pipeline variables:
# - BUILD_POOL - Azure DevOps build pool to use
# - AZURE_CLIENT_ID_SKU - Service principal ID to PUT the SKU
# - AZURE_CLIENT_SECRET_SKU - Service principal secret to PUT the SKU
# - AZURE_TENANT_ID_SKU - tenant ID to PUT the SKU
# - AZURE_CLIENT_ID_VHD - Service principal ID to build the vhd
# - AZURE_CLIENT_SECRET_VHD - Service principal secret to build the vhd
# - AZURE_SUBSCRIPTION_ID_VHD - Subscription ID to build the vhd
# - AZURE_TENANT_ID_VHD - tenant ID to build the vhd
# - DAYS_OLD - consider deleting resources older than this many days
# - DEBUG - whether or not to print script debug output
# - DRY_RUN - whether or not to actually delete resources
# - PUB_VERSION - version of pub command-line tool to use

trigger: none

schedules:
  - cron: "0 2 * * *"
    displayName: "nightly cleanup"
    always: true
    branches:
      include:
        - main

stages:
  - stage: clean
    jobs:
    - job:
      timeoutInMinutes: 120
      pool:
        name: $(BUILD_POOL)
      steps:
      - script: |
          ./scripts/delete-unused-storage.sh
        displayName: Cleaning up unused storage
        workingDirectory: '$(system.defaultWorkingDirectory)/images/capi/packer/azure'
        env:
          AZURE_CLIENT_SECRET: $(AZURE_CLIENT_SECRET)
          AZURE_CLIENT_SECRET_VHD: $(AZURE_CLIENT_SECRET_VHD)
      variables:
        AZURE_CLIENT_ID: $(AZURE_CLIENT_ID_SKU)
        AZURE_CLIENT_SECRET: $(AZURE_CLIENT_SECRET_SKU)
        AZURE_TENANT_ID: $(AZURE_TENANT_ID_SKU)
